import random

pregunta_teoria = {
    {"pregunta" : "¿Que funcion se utiliza para mostrar informacion en pantalla?",
    "opciones" : {"show()", "print()", "display()", "write()"}, "respuesta" : "print()"},
    {"pregunta" : "¿Que simbolo se utiliza para asignar un valor a una variable?",
    "opciones" : {"==",":","=","=>"}, "respuesta" : "=="},
    {"pregunta" : "¿Cual de los siguientes valores es un numero entero?", 
    "opciones" : {"'25'","25.5","true","25"}, "respuesta" : "25"},
    {"pregunta" : "¿Que tipo de dato representa los valores 'True' y 'False'?", 
    "opciones" : {"boolean","bool","logic","bit"}, "respuesta" : "boolean"},
    {"pregunta" : "¿Que estructura se utiliza para almacenar varios valores ordenados y modificables?", 
    "opciones" : {"tupla","diccionario","lista","conjunto"}, "respuesta" : "lista"},
    {"pregunta" : "¿Cual es el indice del primer elemento de una lista?", 
    "opciones" : {"0","1","-1","first"}, "respuesta" : "0"},
    {"pregunta" : "¿Como se escribe correctamente una lista en Python?", 
    "opciones" : {"{1, 2, 3}","[1, 2, 3]","(1, 2, 3)","<1, 2, 3>"}, "respuesta" : "[1, 2, 3]"},
    {"pregunta" : "¿Que estructura almacena datos mediante pares clave-valor?", 
    "opciones" : {"lista","diccionario","tupla","cadena"}, "respuesta" : "diccionario"},
    {"pregunta" : "¿Que palabra reservada se utiliza para crear una condicion?", 
    "opciones" : {"when","if","check","condition"}, "respuesta" : "if"},
    {"pregunta" : "¿Que palabras se utiliza cuando se desea comprobar otra condicion?", 
    "opciones" : {"else if","elseif","elif","otherwise"}, "respuesta" : "elif"},
    {"pregunta" : "¿Que palabra se ejecuta cuando ninguna condicion anterior se cumple?", 
    "opciones" : {"finally","default","else","last"}, "respuesta" : "else"},
    {"pregunta" : "¿Que ciclo se utiliza normalmente para recorrer los elementos de una coleccion?", 
    "opciones" : {"repeat","loop","for","each"}, "respuesta" : "for"},
    {"pregunta" : "¿Que siclo se repite mientras una condicion sea verdadera?", 
    "opciones" : {"while","during","repeat","until"}, "respuesta" : "while"},
    {"pregunta" : "¿Que palabra se utiliza para definir una funcion?", 
    "opciones" : {"function","define","def","func"}, "respuesta" : "def"},
    {"pregunta" : "¿Que palabra se utiliza para devolver el resultado desde una funcion?", 
    "opciones" : {"send","return","output","back"}, "respuesta" : "return"},
    {"pregunta" : "¿Que palabra se utiliza para importar una libreria o modulo?", 
    "opciones" : {"import","include","require","using"}, "respuesta" : "import"},
    {"pregunta" : "¿Que simbolo se utiliza para escribir un comentario de una linea?", 
    "opciones" : {"//","<!--","#","--"}, "respuesta" : "#"},
    {"pregunta" : "¿Que funcion permite conocer el tipo de dato de un valor?", 
    "opciones" : {"typeof()","type()","datatype()","classof()"}, "respuesta" : "typeof()"},
    {"pregunta" : "¿Que instruccion se utiliza normalmente para capturar datos escritos por el usuario?", 
    "opciones" : {"get()","scan()","input()","read()"}, "respuesta" : "input()"},
    {"pregunta" : "¿?", 
    "opciones" : {"","","",""}, "respuesta" : ""},
    {"pregunta" : "¿?", 
    "opciones" : {"","","",""}, "respuesta" : ""},
    {"pregunta" : "¿?", 
    "opciones" : {"","","",""}, "respuesta" : ""},
    {"pregunta" : "¿?", 
    "opciones" : {"","","",""}, "respuesta" : ""},
    {"pregunta" : "¿?", 
    "opciones" : {"","","",""}, "respuesta" : ""},
    {"pregunta" : "¿?", 
    "opciones" : {"","","",""}, "respuesta" : ""},
    {"pregunta" : "¿?", 
    "opciones" : {"","","",""}, "respuesta" : ""},
    {"pregunta" : "¿?", 
    "opciones" : {"","","",""}, "respuesta" : ""},
    {"pregunta" : "¿?", 
    "opciones" : {"","","",""}, "respuesta" : ""},
    {"pregunta" : "¿?", 
    "opciones" : {"","","",""}, "respuesta" : ""},
    {"pregunta" : "¿?", 
    "opciones" : {"","","",""}, "respuesta" : ""}
}